### ISSUE TITLE
Issue with clang build

### ISSUE THREAD

**Issue by maxime-esa** [AdaCore/gprconfig_kb#1]
This issue is a follow-up of the ticket raised here: https://github.com/AdaCore/gprbuild/issues/60

I experience issues with the clang support, which (randomly) replaces gcc if both are installed in /usr/bin.
To reporoduce the problem, I removed `gcc` and `gnatgcc` from `/usr/bin` in order to make sure that clang is triggered.

Create a simple project file:
```
 $ cat foo.gpr 
 project Foo is
    for Source_Dirs use  (".", "include");
    for Languages use ("C");
    for Main use ("main.c");
  end foo;
```
Add an  `include` folder and add a dummy "hello.h" file (it can be empty).
Create main.c:
```
 $ cat main.c
  #include "hello.h"
  int main(void) { }
```

And run gprbuild to get the error:

```
$ gprbuild -v -P foo.gpr 
Changing to object directory of "Foo": "/root/tmp/"
/usr/bin/clang -c -x c -specs=/tmp/GNAT-TEMP-000004.TMP /root/tmp/main.c
clang: warning: argument unused during compilation: '-specs=/tmp/GNAT-TEMP-000004.TMP' [-Wunused-command-line-argument]
/root/tmp/main.c:1:10: fatal error: 'hello.h' file not found
#include "hello.h"
         ^~~~~~~~~
``` 

If you put gcc or gnatgcc back, the build works.

The problem arises with gprbuild from debian buster:

```
$ gprbuild --version
GPRBUILD Community 2018 (20180524) (x86_64-pc-linux-gnu)
Copyright (C) 2004-2018, AdaCore
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by fedor-rybin** [comment]
Hello.
We have [enforced](https://github.com/AdaCore/gpr/commit/09e23c5bd964fbb81667bd1eca779c7e8febaaec) the alphabetical sorting of all compiler candidates from same directory in gpr2, this should eliminate the ambiguity you see when using gprconfig that comes from gpr2.
